source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'json'
gem 'puma'
gem 'rack'
gem 'rackup'

group :development do
  gem 'shotgun'
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end
